[2023-07-14 12:32:52] INFO : => COVID PROJECT <= (main.py:181)
[2023-07-14 12:32:52] INFO : Starting ETL for Covid Data... (main.py:201)
[2023-07-14 12:32:52] INFO : => STARTING EXTRACT... (main.py:49)
[2023-07-14 12:32:52] ERROR : File not found at path: /data/raw_data/covid-raw.csv (extract.py:53)
[2023-07-14 12:34:58] INFO : => COVID PROJECT <= (main.py:181)
[2023-07-14 12:34:58] INFO : Starting ETL for Covid Data... (main.py:201)
[2023-07-14 12:34:58] INFO : => STARTING EXTRACT... (main.py:49)
[2023-07-14 12:35:13] INFO : Data extracted successfully from the URL. (extract.py:27)
[2023-07-14 12:35:13] INFO : Done extracting data from the URL. (main.py:61)
[2023-07-14 12:35:13] INFO : Extract process for Covid - CPU usage 8.4% (main.py:68)
[2023-07-14 12:35:13] INFO : Extract process for Covid - function took : 14.95 seconds (main.py:69)
[2023-07-14 12:35:13] INFO : => STARTING TRANSFORM... (main.py:75)
[2023-07-14 12:35:13] INFO : Starting transform with nyt_cases_counties... (main.py:79)
[2023-07-14 12:35:18] INFO : Done transforming nyt_cases_counties. (main.py:81)
[2023-07-14 12:35:18] INFO : Transform process for Covid - CPU usage 13.1% (main.py:90)
[2023-07-14 12:35:18] INFO : Transform process for Covid - function took : 5.26 seconds (main.py:91)
[2023-07-14 12:35:18] INFO : => STARTING VALIDATE... (main.py:97)
[2023-07-14 12:35:18] INFO : Starting data validation with nyt_cases_counties... (main.py:99)
[2023-07-14 12:35:19] WARNING : Data test cases_vs_deaths failed. Death counts cannot exceed case counts. (validate.py:157)
[2023-07-14 12:35:19] DEBUG : Data test unique_records passed. (validate.py:153)
[2023-07-14 12:35:19] DEBUG : Data test no_nulls_test passed. (validate.py:153)
[2023-07-14 12:35:19] DEBUG : Data test cases_range_test passed. (validate.py:153)
[2023-07-14 12:35:19] WARNING : Data test deaths_range_test failed. Deaths must be non-negative and <= 100K. (validate.py:157)
[2023-07-14 12:35:19] WARNING : 3/5 tests passed. (validate.py:165)
[2023-07-14 12:35:21] INFO : validate info saved successfully to data/validate_info_data/covid_validate_info_20230714.csv. (validate.py:130)
[2023-07-14 12:35:21] INFO : Validation process for Covid - CPU usage 11.9% (main.py:107)
[2023-07-14 12:35:21] INFO : Validation process for Covid - function took : 2.44 seconds (main.py:108)
[2023-07-14 12:35:21] INFO : => STARTING LOAD... (main.py:113)
[2023-07-14 12:35:21] INFO : Saving nyt_cases_counties data to local... (main.py:114)
[2023-07-14 12:35:51] INFO : Data saved successfully to data/save_data/covid_20230714.csv. (load.py:52)
[2023-07-14 12:35:51] INFO : Connected to MySQL database... (database_config.py:85)
[2023-07-14 12:35:51] INFO : covid_db database already exists. (database_config.py:183)
[2023-07-14 12:35:51] INFO : covid table is created in covid_db (database_config.py:206)
[2023-07-14 12:37:39] INFO : Data has been loaded to covid_db.covid (database_config.py:234)
[2023-07-14 12:37:39] INFO : nyt_cases_counties data saved to local. (main.py:118)
[2023-07-14 12:37:39] INFO : Load process for Covid - CPU usage 14.9% (main.py:122)
[2023-07-14 12:37:39] INFO : Load process for Covid - function took : 138.69 seconds (main.py:123)
[2023-07-14 12:37:39] INFO : => STARTING CREATE DATA LOGS... (main.py:133)
[2023-07-14 12:37:39] INFO : Starting create data logs (main.py:134)
[2023-07-14 12:37:41] INFO : Data saved successfully to covid_logs.csv . (dataframe_logs.py:108)
[2023-07-14 12:37:41] INFO : Connected to MySQL database... (database_config.py:85)
[2023-07-14 12:37:41] INFO : covid_db database already exists. (database_config.py:183)
[2023-07-14 12:37:41] INFO : covid_logs table is created in covid_db (database_config.py:206)
[2023-07-14 12:37:41] INFO : Data has been loaded to covid_db.covid_logs (database_config.py:234)
[2023-07-14 12:37:41] INFO : Done creating data logs (main.py:137)
[2023-07-14 12:37:41] INFO : => SESSION SUMMARY... (main.py:140)
[2023-07-14 12:37:41] INFO : RAM memory 63.1% used (main.py:144)
[2023-07-14 12:37:41] INFO : Average CPU usage 12.075% (main.py:145)
[2023-07-14 12:37:41] INFO : Multiple threads took : 163.26 seconds (main.py:146)
[2023-07-14 12:37:41] INFO : => SEND DATA VALIDATION EMAIL... (main.py:149)
[2023-07-14 12:37:41] INFO : data/validate_info_data/covid_validate_info_20230714.csv copied to the data/email-data successfully. (email_config.py:68)
[2023-07-14 12:37:41] INFO : data/log_info_data/covid_logs_20230714.log copied to the data/email-data successfully. (email_config.py:68)
[2023-07-14 12:37:41] INFO : Log file 'covid_logs_20230714.log' converted to text file 'covid_logs_20230714.txt' successfully. (email_config.py:126)
[2023-07-14 12:37:41] INFO : Log files processed successfully. (email_config.py:153)
[2023-07-14 12:37:41] INFO : Log files deleted successfully. (email_config.py:181)
[2023-07-14 12:37:42] INFO : Successfully connected to the server (email_config.py:299)
[2023-07-14 12:37:42] INFO : The email has been sent (email_config.py:361)
[2023-07-14 12:37:43] INFO : The email has been sent (email_config.py:361)
[2023-07-14 12:37:43] INFO : Files in the directory deleted successfully. (email_config.py:39)
[2023-07-14 12:37:43] INFO : Done running ETL for Covid Data (main.py:203)
[2023-07-14 13:38:25] INFO : => COVID PROJECT <= (main.py:181)
[2023-07-14 13:38:25] INFO : Starting ETL for Covid Data... (main.py:201)
[2023-07-14 13:38:25] INFO : => STARTING EXTRACT... (main.py:49)
[2023-07-14 13:38:25] INFO : Data read successfully from the local CSV file. (extract.py:50)
[2023-07-14 13:38:25] INFO : Done reading CSV data from local. (main.py:53)
[2023-07-14 13:38:25] INFO : Extract process for Covid - CPU usage 5.5% (main.py:68)
[2023-07-14 13:38:25] INFO : Extract process for Covid - function took : 0.0 seconds (main.py:69)
[2023-07-14 13:38:25] INFO : => STARTING TRANSFORM... (main.py:75)
[2023-07-14 13:38:25] INFO : Starting transform with nyt_cases_counties... (main.py:79)
[2023-07-14 13:38:25] INFO : Done transforming nyt_cases_counties. (main.py:81)
[2023-07-14 13:38:25] INFO : Transform process for Covid - CPU usage 6.7% (main.py:90)
[2023-07-14 13:38:25] INFO : Transform process for Covid - function took : 0.01 seconds (main.py:91)
[2023-07-14 13:38:25] INFO : => STARTING VALIDATE... (main.py:97)
[2023-07-14 13:38:25] INFO : Starting data validation with nyt_cases_counties... (main.py:99)
[2023-07-14 13:38:25] WARNING : Data test cases_vs_deaths failed. Death counts cannot exceed case counts. (validate.py:157)
[2023-07-14 13:38:25] DEBUG : Data test unique_records passed. (validate.py:153)
[2023-07-14 13:38:25] WARNING : Data test no_nulls_test failed. All values are expected to be non-null. (validate.py:157)
[2023-07-14 13:38:25] DEBUG : Data test cases_range_test passed. (validate.py:153)
[2023-07-14 13:38:25] WARNING : Data test deaths_range_test failed. Deaths must be non-negative and <= 100K. (validate.py:157)
[2023-07-14 13:38:25] CRITICAL : 2/5 tests passed. (validate.py:167)
[2023-07-14 13:38:25] INFO : validate info saved successfully to data/validate_info_data/covid_validate_info_20230714.csv. (validate.py:130)
[2023-07-14 13:38:25] INFO : Validation process for Covid - CPU usage 5.3% (main.py:107)
[2023-07-14 13:38:25] INFO : Validation process for Covid - function took : 0.01 seconds (main.py:108)
[2023-07-14 13:38:25] INFO : => STARTING LOAD... (main.py:113)
[2023-07-14 13:38:25] INFO : Saving nyt_cases_counties data to local... (main.py:114)
[2023-07-14 13:38:25] INFO : Data saved successfully to data/save_data/covid_20230714.csv. (load.py:52)
[2023-07-14 13:38:25] INFO : Connected to MySQL database... (database_config.py:85)
[2023-07-14 13:38:25] INFO : covid_db database already exists. (database_config.py:183)
[2023-07-14 13:38:25] INFO : covid table is created in covid_db (database_config.py:206)
[2023-07-14 13:38:25] INFO : Data has been loaded to covid_db.covid (database_config.py:234)
[2023-07-14 13:38:25] INFO : nyt_cases_counties data saved to local. (main.py:118)
[2023-07-14 13:38:25] INFO : Load process for Covid - CPU usage 6.7% (main.py:122)
[2023-07-14 13:38:25] INFO : Load process for Covid - function took : 0.17 seconds (main.py:123)
[2023-07-14 13:38:25] INFO : => STARTING CREATE DATA LOGS... (main.py:133)
[2023-07-14 13:38:25] INFO : Starting create data logs (main.py:134)
[2023-07-14 13:38:25] INFO : Data saved successfully to covid_logs.csv . (dataframe_logs.py:108)
[2023-07-14 13:38:25] INFO : Connected to MySQL database... (database_config.py:85)
[2023-07-14 13:38:25] INFO : covid_db database already exists. (database_config.py:183)
[2023-07-14 13:38:25] INFO : covid_logs table is created in covid_db (database_config.py:206)
[2023-07-14 13:38:25] INFO : Data has been loaded to covid_db.covid_logs (database_config.py:234)
[2023-07-14 13:38:25] INFO : Done creating data logs (main.py:137)
[2023-07-14 13:38:25] INFO : => SESSION SUMMARY... (main.py:140)
[2023-07-14 13:38:25] INFO : RAM memory 63.2% used (main.py:144)
[2023-07-14 13:38:25] INFO : Average CPU usage 6.05% (main.py:145)
[2023-07-14 13:38:25] INFO : Multiple threads took : 0.25 seconds (main.py:146)
[2023-07-14 13:38:25] INFO : => SEND DATA VALIDATION EMAIL... (main.py:149)
[2023-07-14 13:38:25] INFO : data/validate_info_data/covid_validate_info_20230714.csv copied to the data/email-data successfully. (email_config.py:68)
[2023-07-14 13:38:25] INFO : data/log_info_data/covid_logs_20230714.log copied to the data/email-data successfully. (email_config.py:68)
[2023-07-14 13:38:25] INFO : Log file 'covid_logs_20230714.log' converted to text file 'covid_logs_20230714.txt' successfully. (email_config.py:126)
[2023-07-14 13:38:25] INFO : Log files processed successfully. (email_config.py:153)
[2023-07-14 13:38:25] INFO : Log files deleted successfully. (email_config.py:181)
[2023-07-14 13:38:26] INFO : Successfully connected to the server (email_config.py:299)
[2023-07-14 13:38:26] INFO : The email has been sent (email_config.py:361)
[2023-07-14 13:38:27] INFO : The email has been sent (email_config.py:361)
[2023-07-14 13:38:27] INFO : Files in the directory deleted successfully. (email_config.py:39)
[2023-07-14 13:38:27] INFO : Done running ETL for Covid Data (main.py:203)
